name: Deploy Site

on:
  push:
    branches: [master]
    paths:
      - '.github/**'
      - 'packages/fnx-ui/site/**'
      - 'packages/fnx-ui/src/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm run bootstrap

      - name: Build Site
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run build:site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: packages/fnx-ui/dist-site
