name: Deploy Site

on:
  push:
    branches: [master]
    paths:
      - 'packages/fnx-ui/site/**'
      - 'packages/fnx-ui/src/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm run bootstrap

      - name: Build Site
        run: npm run build:site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: packages/fnx-ui/dist-site
