name: Sync to Gitee

on:
  push:
    branches: [master, gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # GitHub 源仓库地址
          source-repo: git@github.com:Rockcookies/fnx-ui.git
          # Gitee 目标仓库地址
          destination-repo: git@gitee.com:rockcookies/fnx-ui.git
